# Copyright (c) 2023 The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1
      with:
        override: true
        toolchain: stable

    - uses: Swatinem/rust-cache@v2

    - uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: latest

    - name: Build docs
      run: |
        cargo run --package book
        mdbook build contrib/book/build

    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_branch: gh-pages
        publish_dir: contrib/book/build/html
